# Generated by Django 4.1.5 on 2023-07-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_logger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='date',
            field=models.DateField(help_text='year-month-day'),
        ),
        migrations.AlterField(
            model_name='logger',
            name='email',
            field=models.EmailField(help_text='abc@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='logger',
            name='time',
            field=models.TimeField(help_text='24 hour format'),
        ),
    ]
