# Generated by Django 4.1.5 on 2023-07-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_logger_date_alter_logger_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='desc',
        ),
        migrations.AlterField(
            model_name='logger',
            name='date',
            field=models.DateField(),
        ),
    ]
