# Generated by Django 4.1.5 on 2023-07-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_remove_menu_desc_alter_logger_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
