# Generated by Django 4.1.5 on 2023-07-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='desc',
            field=models.TextField(max_length=200),
        ),
    ]
