# Generated by Django 4.1.5 on 2023-07-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_alter_menu_items_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
