# Generated by Django 4.1.5 on 2023-07-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_delete_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='desc',
            field=models.TextField(),
        ),
    ]
