# Generated by Django 4.1.5 on 2023-07-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_alter_menu_items_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
